### ISSUE TITLE
403 Forbidden returned when loading images with the image template tag

### ISSUE THREAD

**Issue by gregorvolkmann** [francescortiz/image#3]
The browser can not load nor does django render the requested image to the local filesystem. The referenced image in the DOM with its token is not created in the `IMAGE_CACHE_ROOT`.

### Example:
**settings.py:**
```
[...]

INSTALLED_APPS = (
    [...]
    'image',
    'core',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
)

[...]

DEBUG = True
TEMPLATE_DEBUG = Tru
SETTINGS_DIR = os.path.dirname(__file__)
PROJECT_PATH = os.path.abspath(os.path.join(SETTINGS_DIR, os.pardir))
IMAGE_CACHE_ROOT = os.path.join(PROJECT_PATH, 'image')

[...]
```
**urls.py:**
```
[...]
url(r'^image/', include('image.urls')),
```
**page.html:**
```
{% load img %}
[...]
<img class="img-responsive img-thumbnail" src="{% image object.image 'width=300&height=170' %}" />
[...]
```

**HTML Output:**
```
<img class="img-responsive img-thumbnail" src="/image/object/image-name.jpg/image_token_c7e127e385c3f007ecb0432d01e0eb516963bcc1">
```

**localhost:8000/image/object/image-name.jpg/image_token_c7e127e385c3f007ecb0432d01e0eb516963bcc1:**
```
Forbidden
```

*Although the `DEBUG` setting is turned on, the visited image url returns only `Forbidden`.*

How would a working settings.py look like?

**Installed packages:**
```
(venv) User$ pip freeze
Django==1.7
Pillow==2.7.0
argparse==1.2.1
django-versatileimagefield==0.5.4
image==1.3.4
psycopg2==2.5.4
wsgiref==0.1.2
```

**Comment by francescortiz** [comment]
The Forbidden message is probably caused by the lack of sessions in your setup. Can you verify this? In case it is afirmative I will update the documentation and the error message to reflect the situation.

On the other hand, if you don't want to use sessions you can the parameter "&autogen=true". This will cause the image to be precached and served without the need for sessions.

**Comment by gregorvolkmann** [comment]
This is not the case, my Middleware has sessions enabled:
'''
MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
)
'''

**Comment by gregorvolkmann** [comment]
I turned `autogen=true`, **it works**. First of all, thank you very much for taking your time for this Issue.

How would your image app be used without `autogen=true`? What are the benefits and why isn't it defaulted to `true`?

**Comment by gregorvolkmann** [comment]
Oh dear, I love your App! :)

**Comment by gregorvolkmann** [comment]
@francescortiz your next german Bratwurst is on me @ChangeTip.

**Comment by changetip** [comment]
Hi @francescortiz, @gregorvolkmann sent you a Bitcoin tip worth 1 Bratwurst (10,926 bits/€2.50), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/679054)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by francescortiz** [comment]
What autogen=true does is to generate the images during the template render phase. Without autogen=true images are rendered on demand. In order to render images on demand we need sessions to make sure that nothing will be rendered unless it was requested by the template. In order words, the session stores a list of all the images that user could want to generate for the given session. Once the image has been generated, it is taken from cache.

autogen=true was added to be able to use image on html to be used on e-mails. It is applicable to any other case when the user who is going to watch the image doesn't have a session prior to watching the image.

I also use autogen=true when using Amazon S3, since there is no way to know when the user's browser will request the images. For this case I use a storage that works both on S3 and locally. Locally only creates symlinks. This allows {% image %} tag to work fast and take profit of S3 without the need of precaching images with a shell command. I will add this storage on the next update.

By the way, thank you for the tip!

**Comment by gregorvolkmann** [comment]
I will test autogen=False tomorrow, with an eye on the session middleware.

**Comment by francescortiz** [comment]
I build a project from scratch. I found the problem. 'django.template.context_processors.request' in order to give access to sessions to the template tag.

I made image show a warning when 'django.template.context_processors.request' is not in TEMPLATE_CONTEXT_PROCESSORS if running in a DEBUG environment.
